server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/workspace
    sql-script-encoding: UTF-8
    username: workspace
    password: 123qweas