spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testalembic
    username: work
    password: 123qweas
    hikari:
      auto-commit: true
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 40
      maximum-pool-size: 64
    sql-script-encoding: utf-8
    initialization-mode: never
#    schema:
#      - classpath:sql/schema.sql
#      - classpath:sql/import.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: david.wang@kyperdata.com
    password: 123qweas
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
#  freemarker:
#      recognize_standard_file_extensions: true
#      classpath: /templates
#    content-type: text/html
#    suffix: .html