server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/workspace
    sql-script-encoding: UTF-8
    username: workspace
    password: 123qweas
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database: postgresql
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  scheduler:
    enable: false
  cache:
    cache-names: getTime,currentTimeMillis
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5s
