server:
  port: 8080
spring:
  application:
    name: spring-boot-example-service
  profiles:
    active: simple
  boot:
    admin:
      client:
        url: http://localhost:8081/
        instance:
          metadata:
            name: ${spring.security.user.name}
            password: ${spring.security.user.password}
            role: ${spring.security.user.role}
  cache:
    cache-names: getTime,currentTimeMillis
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5s
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
scheduler:
  enable: false